

-- -----------------------------------------------------
-- Table APP.oos
-- -----------------------------------------------------
CREATE  TABLE  APP.oos (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
  name VARCHAR(45) NOT NULL ,
  template SMALLINT  NOT NULL DEFAULT 0);



-- -----------------------------------------------------
-- Table APP.oosItem
-- -----------------------------------------------------
CREATE  TABLE  APP.oosItem (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(45) NOT NULL ,
  description LONG VARCHAR ,
  item_type INT NOT NULL ,
  oos INT NOT NULL ,
  CONSTRAINT fk_oosItem_OOS1
    FOREIGN KEY (oos )
    REFERENCES APP.oos (id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE INDEX fk_oosItem_OOS1 ON APP.oosItem (oos ASC) ;



-- -----------------------------------------------------
-- Table APP.vlcItem
-- -----------------------------------------------------
CREATE  TABLE APP.vlcItem (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access VARCHAR(10) NOT NULL ,
  oosItem INT NOT NULL ,
  device VARCHAR(100) ,
  file VARCHAR(45) NOT NULL ,
  options VARCHAR(100) ,
  repeating INT ,
  CONSTRAINT fk_vlcItem_oosItem1
    FOREIGN KEY (oosItem )
    REFERENCES APP.oosItem (id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE INDEX fk_vlcItem_oosItem1 ON APP.vlcItem (oosItem ASC) ;



-- -----------------------------------------------------
-- Table APP.songs
-- -----------------------------------------------------
CREATE  TABLE  APP.songs (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(45) NOT NULL ,
  artist VARCHAR(45) );



-- -----------------------------------------------------
-- Table APP.verses
-- -----------------------------------------------------
CREATE  TABLE  APP.verses (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type INT NOT NULL ,
  number INT NOT NULL ,
  text LONG VARCHAR NOT NULL ,
  song INT NOT NULL ,
  CONSTRAINT fk_verses_songs1
    FOREIGN KEY (song )
    REFERENCES APP.songs (id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE INDEX fk_verses_songs1 ON APP.verses (song ASC) ;



-- -----------------------------------------------------
-- Table APP.songItem
-- -----------------------------------------------------
CREATE  TABLE  APP.songItem (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  oosItem INT NOT NULL ,
  song INT NOT NULL ,
  CONSTRAINT fk_songItem_oosItem1
    FOREIGN KEY (oosItem )
    REFERENCES APP.oosItem (id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_songItem_songs1
    FOREIGN KEY (song )
    REFERENCES APP.songs (id )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE INDEX fk_songItem_oosItem1 ON APP.songItem (oosItem ASC) ;


CREATE INDEX fk_songItem_songs1 ON APP.songItem (song ASC) ;




